---
title: "Topic Modeling"
author: "Jingyu Liang"
date: "2022-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(topicmodels) 
library(gutenbergr)
library(dplyr)
library(tidyverse)
library(tidytext)
```


```{r}
gutenberg_metadata %>%
   filter(title == "On the Origin of Clockwork, Perpetual Motion Devices, and the Compass")
book <- gutenberg_download(30001)

book_df <- book%>%
  unnest_tokens(word, text)

book_df<-filter(book_df,!(word %in% c("_ca","de","a.d","1","al") ))

book_df %<>%
  anti_join(stop_words) %>%
  count(gutenberg_id, word) %>%
  cast_dtm(gutenberg_id, word, n)

ap_lda <- LDA(book_df, k = 3, control = list(seed = 1234))

ap_topics <- tidy(ap_lda, matrix = "beta")

ap_top_terms <- ap_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 10) %>% 
  ungroup() %>%
  arrange(topic, -beta)

ap_top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()
```

#split the chapters
```{r}
# POWER AND MOTION GEARING
# MECHANICAL CLOCKS
# PERPETUAL MOTION AND THE CLOCK BEFORE DE DONDI
# THE MAGNETIC COMPASS AS A FELLOW-TRAVELER FROM CHINA

chap1num <- grep("Power and Motion Gearing", book$text, ignore.case = F)
chap2num <- grep("Mechanical Clocks", book$text, ignore.case = F)
chap3num <- grep("Perpetual Motion and the Clock before de Dondi", book$text, ignore.case = F)
chap4num <- grep("The Magnetic Compass as a Fellow-traveler from China", book$text, ignore.case = F)
end <- grep("Chronological Chart", book$text, ignore.case = F)

chap1 <- book %>% slice(chap1num:chap2num-1)
chap2 <- book %>% slice(chap2num:chap3num-1)
chap3 <- book %>% slice(chap3num:chap4num-1)
chap4 <- book %>% slice(chap4num:end-1)

```


